create database Retail_data

USE Retail_data

-- Data Preparation and Understanding
SELECT * FROM Customer
SELECT * FROM Product_Category
SELECT * FROM Transactions

--Q1. What is the total number of rows in each of the 3 tables in the database?
-- BEGIN  

	SELECT 'Customer' [No of Records], COUNT(*) FROM Customer UNION all 
	SELECT 'Product_Category' [No of Records], COUNT(*) FROM Product_Category UNION all
	SELECT 'Transactions' [No of Records], COUNT(*) FROM Transactions  

-- END 

--Q2. What is the total number of transactions that have a return? 
-- BEGIN 

	SELECT COUNT(Qty) FROM Transactions
	WHERE Qty > 0

-- END 

--Q3. Convert the date variables into valid date formats. 
-- BEGIN 

-- Date formatting is done while importing the data from excel. 

-- END 

--Q4. What is the time range of the transaction data available for analysis? 
-- BEGIN 

	SELECT 
	DATEDIFF(DAY, MIN(tran_date), MAX(tran_date)) AS Days,
	DATEDIFF(MONTH, MIN(tran_date), MAX(tran_date)) AS Months,
	DATEDIFF(YEAR, MIN(tran_date), MAX(tran_date)) AS Years
	FROM Transactions; 

-- END

--Q5. Which product category does the sub-category “DIY” belong to?
-- BEGIN 
	
	SELECT prod_cat 
	FROM Product_Category
	WHERE prod_subcat = 'DIY'

-- END 

-- Data Analysis --

--Q1. Which channel is most frequently used for transactions?
-- BEGIN 

	SELECT TOP 1 Store_type , Count(transaction_id)[No of Transaction] FROM Transactions 
	GROUP BY Store_type 
	ORDER BY COUNT(transaction_id) desc 

-- END 

--Q2. What is the count of Male and Female customers in the database?
-- BEGIN 
	
	SELECT Gender, COUNT(*) as CustomerCount 
	FROM Customer
	GROUP BY Gender;

-- END 

--Q3. From which city do we have the maximum number of customers and how many?
-- BEGIN 
	
	SELECT TOP 1 city_code, COUNT(customer_id) as customercount FROM Customer
	GROUP BY city_code
	ORDER BY COUNT(customer_Id) desc

-- END 

-- Q4. How many sub-categories are there under the Books category?
-- BEGIN 

	SELECT prod_cat, COUNT(prod_subcat)[No of Sub-categories] FROM Product_Category
	WHERE prod_cat = 'Books'
	GROUP BY prod_cat

-- END 

--Q5. What is the maximum quantity of products ever ordered?
-- BEGIN 
	
	SELECT MAX(Qty)[maximum quantity of products ever ordered ]
	FROM Transactions

-- END 

--Q6. What is the net total revenue generated in categories Electronics and Books?
-- BEGIN 
	
	SELECT prod_cat, SUM(total_amt) AS Net_total_rev FROM Transactions AS R1
	INNER JOIN Product_Category AS R2 ON R1.prod_cat_code = R2.prod_cat_code AND 
	R1.prod_subcat_code = R2.prod_sub_cat_code 
	WHERE prod_cat IN ('Electronics' , 'Books') 
	GROUP BY prod_cat 

-- END 

--Q7. How many customers have >10 transactions with us, excluding returns? 
-- BEGIN 

	SELECT cust_id, COUNT(transaction_id) AS no_of_transactions FROM Transactions 
	WHERE total_amt > 0
	GROUP BY cust_id
	HAVING COUNT(transaction_id) > 10  

-- END 

--Q8. What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?
-- BEGIN 

	SELECT prod_cat, R2.store_type, SUM(R2.total_amt) AS Combined_revenue FROM Product_Category AS R1 
	INNER JOIN Transactions R2 
	ON R1.prod_cat_code = R2.prod_cat_code 
	AND R1.prod_sub_cat_code = R2.prod_subcat_code
    WHERE prod_cat IN ('Electronics' , 'Clothing') 
	AND Store_type = 'Flagship store'
	GROUP BY prod_cat, R2.Store_type

-- END 

--Q9. What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat.
-- BEGIN

	SELECT prod_subcat, SUM(R2.total_amt) AS total_revenue FROM Product_Category as R1
	LEFT JOIN Transactions AS R2 
	ON R1.prod_cat_code = R2.prod_cat_code 
	AND R1.prod_sub_cat_code = R2.prod_subcat_code 
	LEFT JOIN Customer AS R3 
	ON R3.customer_Id = R2.cust_id 
	WHERE Gender = 'M' AND prod_cat = 'Electronics'
	GROUP BY prod_subcat

-- END 


--Q10. What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?
-- BEGIN 

	SELECT TOP 5 prod_subcat,
	(SUM(CASE WHEN total_amt > 0 THEN total_amt END)/SUM(total_amt))*100 AS Sales_percentage,
	ABS (SUM(CASE WHEN total_amt < 0 THEN total_amt END)/SUM(total_amt))*100 AS Return_percentage
	FROM Product_Category INNER JOIN Transactions 
	ON Product_Category.prod_sub_cat_code = Transactions.prod_subcat_code 
	AND Product_Category.prod_cat_code = Transactions.prod_cat_code 
	GROUP BY prod_subcat 
	ORDER BY Sales_percentage desc 

-- END 

/*Q11. For all customers aged between 25 to 35 years find what is the net total revenue 
generated by these consumers in last 30 days of transactions from max 
transaction date available in the data?*/
-- BEGIN 

	SELECT SUM(total_amt) AS total_sales FROM Customer AS R1 
	INNER JOIN Transactions AS R2 
	ON R1.customer_Id = R2.cust_id 
	WHERE DOB BETWEEN DATEADD(YEAR, -35,(SELECT MAX(tran_date) FROM Transactions))
	AND DATEADD(YEAR, -25,(SELECT MAX (tran_date) FROM Transactions)) AND
	tran_date >= (SELECT DATEADD(DAY, -30, MAX(tran_date)) FROM Transactions) 

-- END 

--Q12. Which product category has seen the max value of returns in the last 3 months of transactions?
-- BEGIN 

	SELECT prod_cat, SUM(total_amt) AS Total_sum FROM Product_Category AS R1 
	INNER JOIN Transactions AS R2
	ON R1.prod_cat_code = R2.prod_cat_code AND 
	R1.prod_sub_cat_code = R2.prod_subcat_code 
	WHERE total_amt < 0 AND tran_date BETWEEN DATEADD(MONTH, -3,(SELECT MAX(tran_date) FROM Transactions))
	AND (SELECT MAX(tran_date) FROM Transactions)
	GROUP BY prod_cat
	ORDER BY Total_sum desc

-- END 

--Q13.Which store-type sells the maximum products; by value of sales amount and by quantity sold?
-- BEGIN 

	SELECT Store_type FROM (SELECT R2.[Store_type], SUM(R2.[total_amt]) [total_sales], SUM(R2.[Qty]) [total_qty]
	FROM [dbo].[Product_Category] R1 , [dbo].[Transactions] R2 
	WHERE R1.[prod_cat_code] = R2.[prod_cat_code]
	AND R1.[prod_sub_cat_code] = R2.[prod_subcat_code] 
	AND R2.[total_amt] > 0 AND R2.[Qty] > 0 
	GROUP BY R2.[Store_type]) y , (SELECT MAX(x.Ttl_amt) Tamt, MAX(x.Ttl_qty) Tqty
	FROM (SELECT R2.[Store_type], SUM(R2.[total_amt]) ttl_amt, SUM(R2.[Qty]) [ttl_qty]
	FROM [dbo].[Product_Category] R1 , [dbo].[Transactions] R2
	WHERE R1.[prod_cat_code] = R2.[prod_cat_code] 
	AND R1.[prod_sub_cat_code] = R2.[prod_subcat_code]
	AND R2.[total_amt] > 0 AND R2.[Qty] > 0
	GROUP BY R2.[Store_type]) x)z 
	WHERE y.total_sales = z.Tamt AND y.total_qty = z.Tqty 

-- END 

--Q14. What are the categories for which average revenue is above the overall average? 
-- BEGIN 

	SELECT prod_cat, AVG(total_amt) AS Average_revenue 
	FROM Transactions AS R1 
	INNER JOIN Product_Category AS R2
	ON R1.prod_cat_code = R2.prod_cat_code 
	AND R1.prod_subcat_code = R2.prod_sub_cat_code 
	GROUP BY prod_cat 
	HAVING AVG(total_amt) > (SELECT AVG(total_amt) FROM dbo.Transactions)  

-- END 

/*Q15.Find the average and total revenue by each subcategory for the categories 
which are among top 5 categories in terms of quantity sold.*/
-- BEGIN 
	
	SELECT prod_cat, prod_subcat, AVG(total_amt) AS Average_revenue, SUM(total_amt) AS total_revenue 
	FROM Transactions AS R1 INNER JOIN Product_Category AS R2 
	ON R1.prod_cat_code = R2.prod_cat_code 
	AND R1.prod_subcat_code = R2.prod_sub_cat_code
	WHERE prod_cat IN 
	(SELECT TOP 5 prod_cat FROM Transactions INNER JOIN Product_Category
	ON R1.prod_cat_code = R2.prod_cat_code 
	GROUP BY prod_cat
	ORDER BY SUM(Qty) desc) 
	GROUP BY prod_cat, prod_subcat

-- END 